// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obqhxrqpxoaiublaoidv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icWh4cnFweG9haXVibGFvaWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mzk3MjQsImV4cCI6MjA3MjMxNTcyNH0.djty3cbe78iEU_2DWgWFpkf_3v_X9U_SzAWOW5i2voE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: (key: string) => {
        const item = localStorage.getItem(key);
        console.log(`Supabase storage getItem(${key}):`, item ? 'Found' : 'Not found');
        return item;
      },
      setItem: (key: string, value: string) => {
        console.log(`Supabase storage setItem(${key}):`, 'Setting session');
        localStorage.setItem(key, value);
      },
      removeItem: (key: string) => {
        console.log(`Supabase storage removeItem(${key}):`, 'Removing session');
        localStorage.removeItem(key);
      }
    },
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    enabled: false
  }
});